# Generated by Django 3.0.7 on 2021-02-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('deuda', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('cliente', models.CharField(max_length=30)),
                ('puntaje', models.IntegerField()),
            ],
        ),
    ]
